[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"pallets/*",
	"runtime",
	"primitives/account",
	"primitives/ext",
	"primitives/xcm",
	"primitives/rpc/*",
	"primitives/currency",
	"primitives/nimbus-primitives",
	"cli-opt",
]
