[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"runtime",
	"primitives",
	"precompiles/balances-erc20",
	"precompiles/batch",
	"precompiles/utils",
	"precompiles/utils/macro",
	"precompiles/utils/tests-external",
]
